<a href="https://colab.research.google.com/github/taadith/python-projects/blob/main/intro-stat-learning/labs/ISLP_Lab_Ch_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Statistical Learning - Lab 02
Dataset provided by Introduction to Statistical Learning
(from this website: https://www.statlearning.com/resources-python)

**Note: Assuming that *Auto.csv* is in same folder as this notebook.**

## Installing libraries

In [ ]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn

zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip


##Basic Commands

The *?* command helps provide information about functions by providing it's respective Docstring. Here's the *print()*'s function Docstring...

In [ ]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [ ]:
print("fit a model with", 11, "variables")

fit a model with 11 variables


In Python, there are three important type of sequences, ordered lists: lists, tuples, and strings. We introduce lists...

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]
x + y

[1, 2, 3, 4, 5, 6]

In Python, lists hold arbitary objects and are added by concatentation, not element-by-element. This makes sense since Python is designed as a general-purpose programming language. Python's data-specific functionality comes from the *numpy* and *pandas* packages!

## Intro to Numerical Python

In [3]:
import numpy as np

###Numpy Arrays

In numpy, an array is a generic term for a multidimensional set, in the non-mathematical sense, of numbers.

In [ ]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

We see that the numpy arrays are added to each other element-by-element instead of being concatenated!!! Yayyy!

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y

array([5, 7, 9])

Besides one-dimensional numpy arrays, we can essentially make a n-dimensional numpy array, where n is any integer greater than or equal to 1 that is computationally possible.

In [ ]:
x_1d = np.array([1, 2])
x_2d = np.array([[1, 2], [3, 4]])
x_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]], [[13, 14], [15, 16]]])

We can observe the dimensions of a numpy array using the attribute *ndim*.

In [ ]:
print("x_1d dimensions:", x_1d.ndim)
print("x_2d dimensions:", x_2d.ndim)
print("x_3d dimensions:", x_3d.ndim)

x_1d dimensions: 1
x_2d dimensions: 2
x_3d dimensions: 3


Along with the dimensions of the numpy array, the shape of the array itself can be observed with the *shape* attribute.

In [ ]:
print("x_1d shape:", x_1d.shape)
print("x_2d shape:", x_2d.shape)
print("x_3d shape:", x_3d.shape)

x_1d shape: (2,)
x_2d shape: (2, 2)
x_3d shape: (4, 2, 2)


The data type stored within the numpy array can be observed using *dtype()*.

In [ ]:
print("x_1d dtype:", x_1d.dtype)
print("x_2d dtype:", x_2d.dtype)
print("x_3d dtype:", x_3d.dtype)

x_1d dtype: int64
x_2d dtype: int64
x_3d dtype: int64


The *reshape()* method returns a new array with the same elements the numpy array that calls.

In [ ]:
np.reshape?

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])
x_reshape = x.reshape(2, 3)
x, x_reshape

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]))

It's important to note that x and x.reshape occupy the same memory region. We can observe this by modifying x_reshape and then observing the two...

In [ ]:
x_reshape[0, 0] = 99
x, x_reshape

(array([99,  2,  3,  4,  5,  6]),
 array([[99,  2,  3],
        [ 4,  5,  6]]))

...heyyyy this reminds me of a pointer

Interestingly, we cannot modify a tuple!

In [ ]:
tup = (1, 2, 3)
tup[0] = 99

TypeError: 'tuple' object does not support item assignment

###Generating random data



The *np.random.normal()* function generates a vector of random normal variables...

In [4]:
np.random.normal?

From the generated Docstring's first line, we see
```
normal(loc=0.0, scale=1.0, size=None)
```
This means that the function, by default, will generate random normal variable(s) with a mean (loc) of 0 and a standard deviation (scale) of 1. Furthermore, a single random variable will be generated unless *size*'s argument is changed.

We will now generate 50 random independent variables from a *N*(0, 1) distribution...

In [5]:
x = np.random.normal(0, 1, 50)
x

array([-0.4600815 , -1.80989936,  0.70360488,  1.86775985,  0.13544004,
       -0.62907902, -0.09785678, -0.5053355 , -0.11537608, -0.89141985,
       -0.18819758,  0.37047941,  0.50489457, -0.1277385 , -0.78041876,
        0.82568674, -1.47226451, -0.55774988, -0.27640874,  1.72365143,
       -0.91208976, -0.33907329, -1.35705379,  1.24235172, -0.25540157,
        0.82453434,  0.35059304,  2.21767574, -0.38664305, -0.33716559,
        0.46643442,  0.79493744, -0.78125698,  0.92871603,  1.32483255,
        2.52579291, -1.65816908, -0.43512185,  0.92680245, -1.31456902,
       -0.01864776,  1.79530208,  0.63388705, -0.74218037,  1.44269068,
       -0.47007315, -0.28273773, -0.25078463,  0.8695218 , -1.35400721])

We can create an array y by adding an independent *N*(0, 1)* random variable to each element of *x*...

In [6]:
y = x + np.random.normal(0, 1, 50)
y

array([-0.697375  , -2.94576022, -0.16933529,  3.11886781, -0.76169832,
        0.25171489, -0.62626379, -1.41851851, -0.45241603, -0.90729981,
        0.93838272, -0.55181272,  0.43129502, -0.06485072, -1.59513593,
       -2.61583712, -1.31959839, -1.23775179, -2.35000655,  1.93984663,
       -1.03665255,  0.74418192, -0.57925272,  1.72516891, -1.35267174,
        0.96941849,  2.62306515,  4.18358021, -0.97805497, -1.88785356,
       -0.9792983 ,  0.87378034, -2.19446012,  0.82756539,  1.50328516,
        3.84131159, -2.4880865 , -1.39189855,  1.52860663, -1.88416669,
        0.53008149,  3.13239337,  0.74468558, -1.04072907,  0.74440286,
       -1.32962651, -2.37172669,  0.36480338,  1.80189316, -1.18771823])

We can calulate the correlation matrix between *x* and *y* using the *np.corrcoef()* function. The off-diagonal elements gives the correlation between *x* and *y*.

In [7]:
np.corrcoef?

In [8]:
np.corrcoef(x, y)

array([[1.        , 0.81017361],
       [0.81017361, 1.        ]])

In order to ensure that the code provides reproducible results, we can set the random seed using *np.random.default_rng()*.

In [9]:
np.random.default_rng?

In [12]:
rng = np.random.default_rng(3)

We can use the *np.mean()*, *np.var()*, and *np.std()* functions to compute the mean, variance, and standard deviation of arrays, respectively.

In [ ]:
np.mean?

In [14]:
x = rng.standard_normal(10)
np.mean(x), x.mean()

(-0.15207811179871472, -0.15207811179871472)

By default, *np.var()* divides by the sample size *n* rather than *n - 1*. For more information, we should inspect the *ddof*, or degrees of freedom, argument seen in *np.var?*

In [16]:
np.var?

By default, *ddof* is set to zero.

In [15]:
np.var(x), x.var(), np.mean((y - y.mean())**2)

(0.2981928977210926, 0.2981928977210926, 2.9004972615377103)

In [ ]:
np.std?

In [17]:
np.sqrt(np.var(y)), np.std(y)

(1.7030846313491619, 1.7030846313491619)

We can also apply the *np.mean()*, *np.var()*, and *np.std()* functions to the rows and columns of a matrix...

In [18]:
X = rng.standard_normal((5, 5))
X

array([[ 0.02425957,  1.54582085,  0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033, -0.24355868,  1.0023136 ],
       [-0.88645994, -0.29172023,  0.88253897,  0.58035002,  0.0915167 ],
       [ 0.67010435, -2.82816231,  1.02130682, -0.95964476, -1.66861984],
       [ 0.27644576,  0.70054489, -0.44476746, -1.07640584,  0.02612483]])

Arrays are row-major ordered, so the first axis (*axis=0*) refers to its rows. This argument is passed into the *mean()* method for the object X...

In [19]:
X.mean(axis=0)

array([ 0.12497497,  0.21231425,  0.3469127 , -0.4408976 , -0.14630074])

We can also just pass in *0* to represent row-major order...

In [20]:
X.mean(0)

array([ 0.12497497,  0.21231425,  0.3469127 , -0.4408976 , -0.14630074])

##Graphics