<a href="https://colab.research.google.com/github/taadith/python-projects/blob/main/intro-stat-learning/labs/ISLP_Lab_Ch_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Statistical Learning - Lab 02
Dataset provided by Introduction to Statistical Learning
(from this website: https://www.statlearning.com/resources-python)

**Note: Assuming that *Auto.csv* is in same folder as this notebook.**

## Installing libraries

In [1]:
!pip3 install pandas
!pip3 install numpy
!pip3 install matplotlib
!pip3 install seaborn

##Basic Commands

The *?* command helps provide information about functions by providing it's respective Docstring. Here's the *print()*'s function Docstring...

In [2]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [3]:
print("fit a model with", 11, "variables")

fit a model with 11 variables


In Python, there are three important type of sequences, ordered lists: lists, tuples, and strings. We introduce lists...

In [4]:
x = [1, 2, 3]
y = [4, 5, 6]
x + y

[1, 2, 3, 4, 5, 6]

In Python, lists hold arbitary objects and are added by concatentation, not element-by-element. This makes sense since Python is designed as a general-purpose programming language. Python's data-specific functionality comes from the *numpy* and *pandas* packages!

## Intro to Numerical Python

In [5]:
import numpy as np

###Numpy Arrays

In numpy, an array is a generic term for a multidimensional set, in the non-mathematical sense, of numbers.

In [6]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

We see that the numpy arrays are added to each other element-by-element instead of being concatenated!!! Yayyy!

In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y

array([5, 7, 9])

Besides one-dimensional numpy arrays, we can essentially make a n-dimensional numpy array, where n is any integer greater than or equal to 1 that is computationally possible.

In [8]:
x_1d = np.array([1, 2])
x_2d = np.array([[1, 2], [3, 4]])
x_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]], [[13, 14], [15, 16]]])

We can observe the dimensions of a numpy array using the attribute *ndim*.

In [9]:
print("x_1d dimensions:", x_1d.ndim)
print("x_2d dimensions:", x_2d.ndim)
print("x_3d dimensions:", x_3d.ndim)

x_1d dimensions: 1
x_2d dimensions: 2
x_3d dimensions: 3


Along with the dimensions of the numpy array, the shape of the array itself can be observed with the *shape* attribute.

In [10]:
print("x_1d shape:", x_1d.shape)
print("x_2d shape:", x_2d.shape)
print("x_3d shape:", x_3d.shape)

x_1d shape: (2,)
x_2d shape: (2, 2)
x_3d shape: (4, 2, 2)


The data type stored within the numpy array can be observed using *dtype()*.

In [11]:
print("x_1d dtype:", x_1d.dtype)
print("x_2d dtype:", x_2d.dtype)
print("x_3d dtype:", x_3d.dtype)

x_1d dtype: int64
x_2d dtype: int64
x_3d dtype: int64


The *reshape()* method returns a new array with the same elements the numpy array that calls.

In [12]:
np.reshape?

Signature:       np.reshape(a, newshape, order='C')
Call signature:  np.reshape(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function reshape at 0x10471eac0>
File:            /opt/homebrew/lib/python3.12/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to t

In [13]:
x = np.array([1, 2, 3, 4, 5, 6])
x_reshape = x.reshape(2, 3)
x, x_reshape

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]))

It's important to note that x and x.reshape occupy the same memory region. We can observe this by modifying x_reshape and then observing the two...

In [14]:
x_reshape[0, 0] = 99
x, x_reshape

(array([99,  2,  3,  4,  5,  6]),
 array([[99,  2,  3],
        [ 4,  5,  6]]))

...heyyyy this reminds me of a pointer

Interestingly, we cannot modify a tuple!

In [15]:
tup = (1, 2, 3)
tup[0] = 99

TypeError: 'tuple' object does not support item assignment

###Generating random data



The *np.random.normal()* function generates a vector of random normal variables...

In [16]:
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

From the generated Docstring's first line, we see
```
normal(loc=0.0, scale=1.0, size=None)
```
This means that the function, by default, will generate random normal variable(s) with a mean (loc) of 0 and a standard deviation (scale) of 1. Furthermore, a single random variable will be generated unless *size*'s argument is changed.

We will now generate 50 random independent variables from a *N*(0, 1) distribution...

In [17]:
x = np.random.normal(0, 1, 50)
x

array([-0.2988098 ,  1.13656839, -0.83604427, -1.17513578,  0.24200445,
        0.72921665,  0.46636153,  0.07944899, -1.06895515, -1.74605688,
        0.86953468, -0.17923164, -0.65397013,  1.02163528, -1.44456498,
        1.04618493,  0.16760689, -0.30878289, -1.80996323,  0.92466979,
       -1.01176653,  0.70194844, -0.50531993, -2.24523804, -1.01634921,
       -0.84611545,  1.70162235,  0.46438403,  0.3315504 , -0.96257138,
       -0.82975303, -1.17909795, -0.4110934 , -0.56816263,  0.49645461,
       -0.96891657, -0.20867109, -0.23443388,  2.02355954,  1.16384657,
        0.71913484,  0.81712338,  0.06378844, -0.37956814, -1.30736696,
        0.95791421,  0.56640903, -2.22512242,  1.39231852,  0.35745135])

We can create an array y by adding an independent *N*(0, 1) random variable to each element of *x*...

In [18]:
y = x + np.random.normal(0, 1, 50)
y

array([-2.19266   ,  0.52347328,  0.69358069, -1.53201857, -0.29897269,
       -1.14301971,  0.23862674,  0.12377136, -1.09668339, -1.74228425,
        2.10149563, -0.35872829, -1.17419925,  1.20733831, -2.26140935,
        0.36646634,  0.42552193, -0.55995585, -2.26371557,  1.79692803,
        0.43505743,  0.58417684, -2.18837782, -1.6002546 , -2.2356637 ,
       -1.44003006,  2.51883067, -0.19647841,  1.4197703 , -1.63774918,
       -1.63155662, -0.2123628 , -1.23378945, -0.58463172, -0.71458969,
       -0.65197011, -0.23129562,  0.1526716 ,  2.43852695,  1.49425987,
       -0.03930412,  0.0736911 , -0.64062332, -1.2937482 , -0.1610559 ,
        0.03315499,  0.41678486, -0.75582846,  1.65162104, -0.21623225])

We can calulate the correlation matrix between *x* and *y* using the *np.corrcoef()* function. The off-diagonal elements gives the correlation between *x* and *y*.

In [19]:
np.corrcoef?

Signature:      
np.corrcoef(
    x,
    y=None,
    rowvar=True,
    bias=<no value>,
    ddof=<no value>,
    *,
    dtype=None,
)
Call signature:  np.corrcoef(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function corrcoef at 0x109b65120>
File:            /opt/homebrew/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py
Docstring:      
Return Pearson product-moment correlation coefficients.

Please refer to the documentation for `cov` for more detail.  The
relationship between the correlation coefficient matrix, `R`, and the
covariance matrix, `C`, is

.. math:: R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} C_{jj} } }

The values of `R` are between -1 and 1, inclusive.

Parameters
----------
x : array_like
    A 1-D or 2-D array containing multiple variables and observations.
    Each row of `x` represents a variable, and each column a single
    observation of all those variables. Also see `rowvar` below.
y : array_like, optional
    An addition

In [20]:
np.corrcoef(x, y)

array([[1.        , 0.74450268],
       [0.74450268, 1.        ]])

In order to ensure that the code provides reproducible results, we can set the random seed using *np.random.default_rng()*.

In [21]:
np.random.default_rng?

Signature:      np.random.default_rng(seed=None)
Call signature: np.random.default_rng(*args, **kwargs)
Type:           cython_function_or_method
String form:    <cyfunction default_rng at 0x10a12fe00>
Docstring:     
default_rng(seed=None)
Construct a new Generator with the default BitGenerator (PCG64).

    Parameters
    ----------
    seed : {None, int, array_like[ints], SeedSequence, BitGenerator, Generator}, optional
        A seed to initialize the `BitGenerator`. If None, then fresh,
        unpredictable entropy will be pulled from the OS. If an ``int`` or
        ``array_like[ints]`` is passed, then all values must be non-negative and will be
        passed to `SeedSequence` to derive the initial `BitGenerator` state. One may also
        pass in a `SeedSequence` instance.
        Additionally, when passed a `BitGenerator`, it will be wrapped by
        `Generator`. If passed a `Generator`, it will be returned unaltered.

    Returns
    -------
    Generator
        The init

In [22]:
rng = np.random.default_rng(3)

We can use the *np.mean()*, *np.var()*, and *np.std()* functions to compute the mean, variance, and standard deviation of arrays, respectively.

In [23]:
np.mean?

Signature:      
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.mean(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function mean at 0x1047518a0>
File:            /opt/homebrew/lib/python3.12/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints,

In [ ]:
x = rng.standard_normal(10)
np.mean(x), x.mean()

By default, *np.var()* divides by the sample size *n* rather than *n - 1*. For more information, we should inspect the *ddof*, or degrees of freedom, argument seen in *np.var?*

In [ ]:
np.var?

By default, *ddof* is set to zero.

In [ ]:
np.var(x), x.var(), np.mean((y - y.mean())**2)

In [ ]:
np.std?

In [ ]:
np.sqrt(np.var(y)), np.std(y)

We can also apply the *np.mean()*, *np.var()*, and *np.std()* functions to the rows and columns of a matrix...

In [ ]:
X = rng.standard_normal((5, 5))
X

Arrays are row-major ordered, so the first axis (*axis=0*) refers to its rows. This argument is passed into the *mean()* method for the object X...

In [ ]:
X.mean(axis=0)

We can also just pass in *0* to represent row-major order...

In [ ]:
X.mean(0)

##Graphics

In Python, it's common practice to use the *matplotlib* library for graphics. This is because Python, itself, was not written with data analysis in mind, so plotting is not intrinsic to the language. We will use *subplots()* from *matplotlib.pyplot* to create the figure and the axes onto which we plot our data.

In [24]:
from matplotlib.pyplot import subplots
subplots?

Matplotlib is building the font cache; this may take a moment.


Signature:
subplots(
    nrows: 'int' = 1,
    ncols: 'int' = 1,
    *,
    sharex: "bool | Literal['none', 'all', 'row', 'col']" = False,
    sharey: "bool | Literal['none', 'all', 'row', 'col']" = False,
    squeeze: 'bool' = True,
    width_ratios: 'Sequence[float] | None' = None,
    height_ratios: 'Sequence[float] | None' = None,
    subplot_kw: 'dict[str, Any] | None' = None,
    gridspec_kw: 'dict[str, Any] | None' = None,
    **fig_kw,
) -> 'tuple[Figure, Any]'
Docstring:
Create a figure and a set of subplots.

This utility wrapper makes it convenient to create common layouts of
subplots, including the enclosing figure object, in a single call.

Parameters
----------
nrows, ncols : int, default: 1
    Number of rows/columns of the subplot grid.

sharex, sharey : bool or {'none', 'all', 'row', 'col'}, default: False
    Controls sharing of properties among x (*sharex*) or y (*sharey*)
    axes:

    - True or 'all': x- or y-axis will be shared among all subplots.
    - False or 